title: Cadabra Engineering Notes
description: Reframing software delivery through contextual intelligence — patterns, infra, and prompt logic.
theme: jekyll/minima
markdown: kramdown
plugins:
  - jekyll-sitemap
google_site_verification: SHFy-UoWVPh0D6sK111wJwzEdpekB4YDsZfx_VRKGBE
