name: Delete layouts folder

on:
  push:
    paths:
      - '_layouts/**'

jobs:
  remove-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Delete _layouts folder
        run: |
          rm -rf _layouts
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Remove _layouts to restore minima theme" || echo "No changes"
          git push
