name: Delete layouts folder

on:
  push:
    paths:
      - '_layouts/**'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete _layouts folder
        run: |
          rm -rf _layouts

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Remove _layouts folder" || echo "No changes to commit"
          git push
